// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  parallax_cards: dynamic(() => import("./ParallaxCard")),
  product_grid: dynamic(() => import("./ProductGrid")),
  video_section: dynamic(() => import("./VideoSection")),
};
